- name: Understanding vars
  hosts: all
  become: yes
  vars:
    USRNM: playuser
    COMM: playname
  tasks: 
    - name: create user
      ansible.builtin.user:
        name: "{{USRNM}}"
        comment: "{{COMM}}"
      register: usrout

    - debug:
        var: usrout.comment

