- hosts: dbservers
  become: yes
  tasks: 
    
    - name: install mariadb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: latest

    - name: start srvice
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes



- hosts: webservers
  become: yes
  tasks:

    - name: install httpd
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: start srvice
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
