- hosts: dbservers
  become: yes
  tasks: 
    
    - name: install mariadb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: latest

    - name: start srvice
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database with name 'accounts'
      mysql_db:
        name: accounts
        state: present

